openapi: 3.0.0
info:
  title: Items API
  description: API for managing items
  version: 1.0.0
  contact:
    name: API Support
    url: https://example.com/support
    email: support@example.com

servers:
  - url: /api
    description: Main API server

paths:
  /items:
    get:
      summary: Get all items
      description: Returns a list of all items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
                  count:
                    type: integer
                    example: 5
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Create a new item
      description: Creates a new item with the given data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: string
                  example: "test"
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete all items
      description: Deletes all items from the database
      responses:
        '200':
          description: All items deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "All items deleted successfully"
                  count:
                    type: integer
                    example: 5
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        data:
          type: string
          example: "test"
        created_at:
          type: string
          format: date-time
          example: "2025-08-31T20:32:46Z"
    
    Error:
      type: object
      properties:
        error:
          type: string
          example: "Error message"
        details:
          type: string
          example: "Detailed error information"
