openapi: "3.0.0"
x-json-schema-faker:
  locale: de
  min-items: 1
  max-items: 3
  fixedProbabilities: false
  optionalsProbability: 1
  fillProperties: false
  alwaysFakeOptionals: false
info:
  version: 1.0.0
  title: MyApi
  license:
    name: MIT
paths:
  /items:
    get:
      summary: List all items
      operationId: listItems
      responses:
        200:
          description: array of items
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Items"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Item:
      required:
        - verb
        - noun
      properties:
          verb:
            type: string
            x-faker: word.verb
          noun:
            type: string
            x-faker: word.noun
    Items:
      type: array
      items:
        $ref: "#/components/schemas/Item"
    Error:
      required:
        - message
      properties:
        message:
          type: string
