name: Playwright Tests

# Disabled by default - run manually from GitHub Actions
on:
  workflow_dispatch:  # Only runs when manually triggered from GitHub UI
  # Uncomment the following lines to enable automatic runs
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    services:
      # Start the application server for testing
      app:
        image: node:20
        ports:
          - 3000:3000
        working-directory: /app
        env:
          NODE_ENV: test
        # Run the app in the background
        options: >-
          --health-cmd "curl -f http://localhost:3000/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - .:/app

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run database migrations
      run: npm run db:migrate
    
    - name: Run Playwright tests
      run: npx playwright test --workers=2
      env:
        NODE_ENV: test
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
